### ISSUE TITLE
Window gaps

### ISSUE THREAD

**Issue by marko-radosavljevic** [Leleat/Tiling-Assist#18]
Oh, what a lovely extension! ^^

Seriously, amazing work, works flawlessly out of the box on gnome 3.36. Wanted to confirm that for you, I'm on 'buntu 20.04.

What do you think about supporting gaps between windows in your extension? It's something I would really love for my gnome experience. Something like[ pop-os shell](https://github.com/pop-os/shell) gaps or[ i3-gaps](https://github.com/Airblader/i3). Because I use dark theme everywhere, windows can blend together, and that looks kinda weird. I also think having that gap is very aesthetically pleasing, and would make your extension unique. It's something that's not easy to get on gnome currently, without extra baggage.

My JS is very weak, but I would be willing to try to implement this if you are interested.

And you should absolutely share this on the Reddit or HackerNews, better tiling for Gnome is a must-have I believe!

**Comment by Leleat** [comment]
Thanks for the feedback :) !

> What do you think about supporting gaps between windows in your extension?

Sure, I'll add it (although probably next year since holidays are always busy). 

> My JS is very weak, but I would be willing to try to implement this if you are interested.

My JS is also weak since I am an accountant by trade xD. If you want to try your hand at it, go ahead. Otherwise I'll do when I am free.

> And you should absolutely share this on the Reddit 

I do plan to make a reddit post to get more testers/users when I hit "1.0". As I said I am no developer, so I still have some questions I need to clear up about JS, some more features to implement and whatnot before "going public".

-----
Out of interest, are you using Wayland or X11? And are you using the current master version or the one from EGO?

Someone made a bugreport on EGO and said that they had occasional GNOME Shell crashes. Ithought it may be Wayland related since I didn't have problems on X11. Unfortunately they never got back to me...

**Comment by marko-radosavljevic** [comment]
I'm using X11, with non-default theme, and [dash-to-panel](https://github.com/home-sweet-gnome/dash-to-panel) extension (panel at the bottom, no top bar), extension v8 from EGO. So far everything is working nicely. Tell me if you need master branch tested for 20.04/3.36. ^^

> I do plan to make a reddit post to get more testers/users when I hit "1.0". As I said I am no developer, so I still have some questions I need to clear up about JS, some more features to implement and whatnot before "going public".

Yup, totally understandable. I will try to help if I can. Enjoy your holidays! ^^

**Comment by Leleat** [comment]
> Tell me if you need master branch tested for 20.04/3.36

Nah, it's fine. Wayland is my main concern currently. (I am testing it on an old machine). 
If you find some bugs in the EGO version though, please test the master branch here. I alread did some minor bugfixes which I haven't uploaded to EGO yet.

**Comment by Leleat** [comment]
implemented with latest commit. 

Not sure, if fully maximized windows should also have gaps. Currently they don't. What do you think @marko-radosavljevic?

**Comment by marko-radosavljevic** [comment]
Honestly, this is killing me. I switched to KDE because it's much more capable and customizable than gnome, but seeing how much progress you made, I want to switch back.. :cry: 

Seriously not cool. ^^

I believe maximized should have no gaps. Are gaps configurable? Users should have the option to turn them on/off, configure gap size in pixels, etc.

Btw, you can find my email in my profile, send me yours if you are comfortable, would like to discuss/share something with you. ^^

**Comment by Leleat** [comment]
> Honestly, this is killing me. I switched to KDE because it's much more capable and customizable than gnome, but seeing how much progress you made, I want to switch back.. :'(
>
> Seriously not cool. ^^

lol, don't worry. I develop this extension for my own use because I was missing features in GNOME. 

I used to use KDE as well. But the customizability in the end drove me to GNOME. I just GNOME's out-of-the-box experience more.
