### ISSUE TITLE
Wide window grab is anchored outside of the window itself

### ISSUE THREAD

**Issue by l3nn4rt** [Leleat/Tiling-Assist#20]
https://streamable.com/zizr4y

**Comment by Leleat** [comment]
Do you happen to use Wayland?

**Comment by l3nn4rt** [comment]
yes

**Comment by Leleat** [comment]
> yes

I am aware of this issue then. I am tracking Wayland problems in #17. So I'll close this. 

I am currently visiting family and only got a laptop running X11. But IIRC that doesn't happen with all apps (only GNOME/GTK?).

Once I am back at my place, I can try to fix it.

**Comment by l3nn4rt** [comment]
yes, GTK apps only AFAIK (at least, it didn't happen with firefox, chromium and vs-code)

**Comment by Leleat** [comment]
Got back home today and I think I have it fixed now (in master)... or at least a passable workaround.
