### ISSUE TITLE
Conky causes preview not to disappear after first DnD

### ISSUE THREAD

**Issue by l3nn4rt** [Leleat/Tiling-Assist#22]
### description
If a conky window is running, first time I tile with DnD the preview does not disappear after drop. Following DnD do not show this behaviour. 

### environment
- GNOME Shell: 3.38.2 (Wayland)
- OS: Arch Linux
- Tiling-Assist: commit bb675a8

### steps
- enable Tiling-Assist
- start conky
- drag-and-drop a window on screen edge

### demo
https://streamable.com/jgu5xi

**Comment by Leleat** [comment]
Fixed by af79d70. App was null for the Conky Desktop window and thus led to a bug prevented the closing of the preview.
