### ISSUE TITLE
Preference to disable the select window popup when snapping a window

### ISSUE THREAD

**Issue by chrisirwin** [Leleat/Tiling-Assist#24]
When snapping a window to a half (whether left/right or top/bottom), this extension pops up a selector to chose another window to snap in the other half.

It would be very nice to disable this, as most often I don't want to snap a specific window to the other space.

It doesn't do this when snapped to a quarter, which is ideal.

**Comment by Leleat** [comment]
Do you use the version from EGO? If so, the current master already gives you the option to disable the popup (via a setting or keybinding)?

**Comment by chrisirwin** [comment]
The one published on extensions.gnome.org.

Thanks.
