### ISSUE TITLE
Updated version on GNOME extensions

### ISSUE THREAD

**Issue by arielsboiardi** [Leleat/Tiling-Assist#29]
Hello, I think this extension is the perfect middle ground option between a full tiling windows manager and plain GNOME (not to mention the only one that seems to consistently work in Wayland). Thanks for this amazing work! 

Unfortunately I would not have noticed how good this extension is if I had not been committed enough as the version on the GNOME extensions portal is seriously crippled. I don't know if it is only a matter of some days delay (it does not seem the case), but please consider updating the version on GNOME extensions the benefits are many: 
- More users will enjoy the full version and realize how good it is: the half baked version on GNOME extensions is not much better that the other alternatives (which is to say that it is not very good).
- The description on GNOME extension does not match the feature set of the extension that actually gets installed, which is a bit sketchy
- As a user I would like automatic updates... Of course I could write a script that git clones on right folder whenever there is a new version, but I would say that the update process of extension on extensions.gnome.org is smoother!

**Comment by Leleat** [comment]
Heh, what a coincidence :)

I did upload a new version abotu 2 weeks ago to EGO (which already got approved recently). Also pushed a new update this week (which is still in the review process).

> (not to mention the only one that seems to consistently work in Wayland)

Wayland kinda behaves weirdly at times, so I had to use some workarounds. Hopefully it all works. Currently the layouts wth attached apps don't work consistently on Wayland.

**Comment by arielsboiardi** [comment]
Oh, I did not know the process required weeks... I'll install the EGO version when the update gets approved. Thanks for you clarification.

**Comment by Leleat** [comment]
> Oh, I did not know the process required weeks...

Sorry, if I was unclear. I didn't mean weeks. Usually the approval process takes only a few days up to a week. One of the devs at EGO needs to manually check all the code changes. IIRC I pushed the latest update yesterday or monday. While taking down the last version. So expect it a new update from EGO soon-ish.
