### ISSUE TITLE
Reduce maximize activation area when top panel is disabled

### ISSUE THREAD

**Issue by seldon1000** [Leleat/Tiling-Assist#34]
**Description**
Please correct me if I'm wrong.
Window maximize action in Gnome is triggered when the cursor's center touches the top panel or, if it's not there, the top edge of the screen. Tiling Assistant uses a much larger trigger area. The problem is that Tiling Assisting doesn't care if the top panel is actually there or not.
This means that, if I use an extension like Dash to Panel, or Bottom Panel, or I simply disable the top panel, Tiling Assistant won't change it's trigger points, giving back a weird UX. It becomes literally impossible to drag windows on the top of the screen, cause there's this large area I can't use without triggering the maximize action. On classic Gnome, I can drag any window all the way to the top from its headerbar/titlebar without problems.

**Steps To Reproduce**
Install Dash to Panel extension and drag a window to the top edge of the screen from its headerbar/titlebar.

**Screenshots/-captures**
Tiling Assistant ON:
![Schermata del 2021-03-04 18-54-16](https://user-images.githubusercontent.com/55358113/110007619-2bf50900-7d1b-11eb-8bad-5e7355c7e586.png)

Tiling Assistant OFF:
![Schermata del 2021-03-04 18-38-07](https://user-images.githubusercontent.com/55358113/110006638-2fd45b80-7d1a-11eb-960a-8d3b2567a7b9.png)
Here, just a couple of pixels higher and I would trigger the maximize action. But, at this point, nothing happens (and nothing should).

**System Info:**
 - Distro (incl. version): Arch Linux
 - GNOME version: 3.38.4
 - XOrg/Wayland: X11

**Comment by Leleat** [comment]
Oops, yeah, the trigger area used the top panel's height. Didn't think about more customized GNOME desktops. Pushed a new commit to use the workarea now and I've also decreased the area from 25 px to 10 px. Can you test the master branch and tell me how you feel about it?

**Comment by seldon1000** [comment]
Great, thanks! I will test it in a few minutes and let you know.

**Comment by seldon1000** [comment]
@Leleat done, this feels just perfect! Testing it, I experienced this same bug https://github.com/Leleat/Tiling-Assist/issues/35 . I wish I could help. BTW, your extension is awesome, you've done a really great work!

**Comment by Leleat** [comment]
> done, this feels just perfect!

> BTW, your extension is awesome, you've done a really great work!

Great to hear, thanks :)
