### ISSUE TITLE
Option to pre-select Layout on startup

### ISSUE THREAD

**Issue by Stephane-30** [Leleat/Tiling-Assist#36]
After starting up the desktop and opening an app (eg browser) it will occupy part of the screen (usually last size and position). When opening a second app (eg terminal) it will sit on top of the browser. When I then initiate 'Tile to empty space' the terminal will just maximise and occupy the whole screen. Any other additional app will just place itself randomly on the screen on top of each other. I then have to manually select a defined 'Layout x' and click through the apps in the Dash to place them.

I suggest to perhaps have an option to pre-select a Layout by default when starting up the desktop. Opening up applications should then result in being automatically placed in the defined tiles.  

My assumption is that a lot of users probably start up their working day with the same application to start with (in my case usually a browser and a terminal.

**Comment by Leleat** [comment]
> When I then initiate 'Tile to empty space' the terminal will just maximise and occupy the whole screen

How do you think/expect that keybinding should work, if there are no other tiled windows? Should it do nothing (and just send a )?

**Comment by Leleat** [comment]
> I suggest to perhaps have an option to pre-select a Layout by default when starting up the desktop. Opening up applications should then result in being automatically placed in the defined tiles.
>
> My assumption is that a lot of users probably start up their working day with the same application to start with (in my case usually a browser and a terminal.

Sounds like a tiling window manager? A tiling window manager might also adress your first issue. Is there a reason why you don't use one / prefer to use my extension?

**Comment by Stephane-30** [comment]
I've tried tiling managers and even installed Regolith but they are all way over the top and too restrictive (ie basically not allowing you to use a combination of key bindings and the mouse - usually key bindings only). 

Your extension works by far the best. I like to continue using my Gnome desktop as it is but with the option to lay out windows into tiles if required rather then contantly resizing and fitting them into the available space. 

Your tiling manager does an excellent job and I will continue using it. As I said - it was just an idea to have an **option** for a default Layout on startup. At the moment the steps are:
1. Starting the desktop
2. Opening the browser and a terminal (or any other apps)
3. Then selecting a Layout (eg Super-1)
4. Then clicking through the Dash to place the windows.

Alternatively selecting one of the user defined Layouts in the tiling manager settings as a 'Default Layout' (this is obviously done only once)

1. Starting the desktop
2. Opening the browser and a terminal which will automatically place themselves into the defined tiles.

Not to worry if this is not possible. It was just a suggestion ;-)

**Comment by Leleat** [comment]
I am not opposed to the idea but it is outside my current abilities. I don't know how to cleanly hook into "startup" of an app.

> Then clicking through the Dash to place the windows.

Well, you can also use the keyboard ;) You don't need to wait for the animations to finish... you can just spam the `space` or `return` key.

**Comment by Stephane-30** [comment]
I think I now understand where the problem with my suggestion is. WTM can only work if at least one application window has been opened. I guess that's also the reason you can't select a Layout before actually opening a window first. 
Sorry, my mistake - lack of understanding how your WTM works. All good now.

**Comment by Leleat** [comment]
Closing this as I don't know how this could be implemented and I am personally not in need of this... So unless someone else opens a pr for it, it won't be be added...
