### ISSUE TITLE
Unable to quarter tile windows, if I move the window to a horizontal edge first

### ISSUE THREAD

**Issue by Turbine1991** [Leleat/Tiling-Assist#38]
**Describe the bug**
After moving a window from its untiled location to a centre horizontal edge of screen, the window will fail to quarter tile if moved there afterwards. Strangely this doesn't appear to be an issue when trying this on a vertical edge.

**Steps To Reproduce**
- Open window
- Move to centre horizontal edge of screen
- Try moving it to a corner, without hitting the top area of screen

**Screenshots/-captures**
![Video](https://media.giphy.com/media/f6UzJh8WQ0BpU7GL1p/giphy.gif)

**System Info:**
 - Pop!_OS 20.10
 - 3.38.3
 - xorg 7.7

**Comment by Leleat** [comment]
I assume you are using the latest version from EGO?

In the previous versions I not only used `global.get_pointer()` but also the window's position to determine when the tile preview should show. When adressing #34 (OP wanted to move windows to the top edge of the screen without activating the tiling) I removed that and only relied on `global.get_pointer()`. 

The reason why I also used the window's position in the past is that `global.get_pointer()` is not accurate when going from the left/right screen edges in to the corners... no idea why. Weirdly, you should be able to tile from those edges, if you use enough "force", i. e. move the mouse very quickly from the edges to the corners... I was hoping that people wouldn't notice this change. I guess I'll add the workaround with the window's position back in. This time I'll make it optional via a setting.

**Comment by Leleat** [comment]
I pushed an commit to master which should improve the behaviour; can you test it? If not, I'll close this and directly upload the new version to EGO.

**Comment by Turbine1991** [comment]
I'm using the latest provided by Gnome Extensions.

How interesting. Perhaps tiling on the tip centre edge of screen makes sense only when a window has been tiled towards the lower half of the screen?

That's strange, even when I move the mouse fast, I often fail. So I spend about 4-5 seconds to ensure I carefully quarter tile a window, rather than rely on memory muscle.

I hope some distro starts to bundle this extension, it's so good.

**Comment by Leleat** [comment]
Note: I didn't make it a settings. But the behaviour should still be improved for the quarters only. So you can still move windows to the top now (like #34 wanted).

**Comment by Leleat** [comment]
> This fix works almost flawlessly.

Thanks for te confirmation.

> And the quarter zone differs from the vertical edge to the horizontal

Can you elaborate? I don't understand what you mean with that?

> The only issue I know of now is not being able to delete a keybind.

Can you please open a separate issue for that so I can better keep track of stuff and help you debug it.

**Comment by c-ridgway** [comment]
> > And the quarter zone differs from the vertical edge to the horizontal
> 
> Can you elaborate? I don't understand what you mean with that?

When my mouse is at the top left corner of the screen, the vertical (top) side has about 10 pixels, whereas the horizontal (left) has about 20 pixels from the edge of the screen. Perhaps it's done on percentages? 40 pixels should be perfect with the default scaling.

> > The only issue I know of now is not being able to delete a keybind.
> 
> Can you please open a separate issue for that so I can better keep track of stuff and help you debug it.

No problem.

**Comment by Leleat** [comment]
> When my mouse is at the top left corner of the screen, the vertical (top) side has about 10 pixels, whereas the horizontal (left) has about 20 pixels from the edge of the screen. Perhaps it's done on percentages? 40 pixels should be perfect with the default scaling.

The top screen half tile uses percentages. The rest uses pixels. I've increased it from 10 for the sides to 40 px per your suggestion. I won't change the top count though. As per #34, some people want to move windows all the way to the top without tiling, so I think 10 px there is fine.

**Comment by c-ridgway** [comment]
In that case, might as well keep it 10. Or even better, a setting. It'll be perfect.

**Comment by Leleat** [comment]
> In that case, might as well keep it 10

I don't like giving a setting for such a minor thing, sorry. If you want to customize it, you can edit lines 534/545 and replace the `10` in the `extensions.js` file.
