### ISSUE TITLE
Unable to remove keybinding

### ISSUE THREAD

**Issue by c-ridgway** [Leleat/Tiling-Assist#39]
**Describe the bug**
After assigning a key bind, there doesn't appear to be a way to put it in the unbound "Disabled" state again.

**Steps To Reproduce**
- Bind a key to ALT + Left
- Now try to clear it, right clicking, pressing escape or delete - none of which will clear it.

**System Info:**
 - OS: Pop!_OS 20.10
 - GNOME version: 3.38.3
 - Extensions version: 13
 - XOrg/Wayland: XOrg

**Comment by Leleat** [comment]
Ah, it's probably not a bug. You need to use `Backspace` (It's also the default for GNOME/GTK).

**Comment by c-ridgway** [comment]
Thank you, I had no idea Gnome uses backspace.
