### ISSUE TITLE
 MPV's windows resize completely wrong when tiled

### ISSUE THREAD

**Issue by seldon1000** [Leleat/Tiling-Assist#40]
**Describe the bug**
MPV's windows resize with completely wrong dimensions and position when I tile them. MPV should add black borders to the image to adapt the window to the desired sizes, but it does not happen when Tiling Assistant is enabled. Whatever media file I open, it can't resize the window correctly.

**Steps To Reproduce**
Open a MPV window and tile it.

**Screenshots/-captures**

https://user-images.githubusercontent.com/55358113/110513539-a0a6b980-8106-11eb-8ec6-c902a43628a7.mp4

**System Info:**
 - Distro (incl. version): Arch
 - GNOME version: 3.38.4
 - Extensions version: 12
 - XOrg/Wayland: X11

**Comment by Leleat** [comment]
Hmm, no idea why that happens. Definitly need help with this

**Comment by seldon1000** [comment]
> Fortunately I don't see anything other than the odd media player doing this. Totem (Gnome's default) seems to be fine.

Yes, I tried gnome-mplayer and celluloid (mpv based) too and both work just fine.

**Comment by Leleat** [comment]
I tried to run mpv but it's constantly crashing on me when I open media with it. So I can't test it. But if it's this

> It appears to be the way this app resizes (by ratio). Because you're setting the width and height, it's ending up with the wrong size.

Maybe try changing line 509 in `~.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/util.js` from 

```
window.move_resize_frame(false, rect.x, rect.y, rect.width, rect.height);
```
to

```
const workArea = window.get_work_area_current_monitor();
if (newRect.height === workArea.height) {
	window.move_frame(false, rect.x, rect.y);
	window.maximize(Meta.MaximizeFlags.VERTICAL);
} else {
	window.move_resize_frame(false, rect.x, rect.y, rect.width, rect.height);
}
```

@seldon1000

**Comment by seldon1000** [comment]
@Leleat 

> Maybe try changing `line 509` in `~.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/util.js` from
> 
> ```
> window.move_resize_frame(false, rect.x, rect.y, rect.width, rect.height);
> ```
> 
> to
> 
> ```
> const workArea = window.get_work_area_current_monitor();
> if (newRect.height === workArea.height) {
> 	window.move_frame(false, rect.x, rect.y);
> 	window.maximize(Meta.MaximizeFlags.VERTICAL);
> } else {
> 	window.move_resize_frame(false, rect.x, rect.y, rect.width, rect.height);
> }
> ```

No luck, it didn't make any difference.

**Comment by Leleat** [comment]
Too bad :/

Just to be sure, you reload GNOME shell?

**Comment by seldon1000** [comment]
Of course I did, I even rebooted the PC to be sure. I finally reverted to the original code because it seemed to add some weird animation when tiling other windows.

**Comment by Turbine1991** [comment]
This issue might be resolved with a MPV update. Assuming this is the same issue.

> Oschowa @Oschowa · 3 months ago
The relevant mpv commit has been reverted and resizing seems fine in general on mutter 3.38.2, so i'll close this.

**Comment by Leleat** [comment]
> The relevant mpv commit has been reverted and resizing seems fine in general on mutter 3.38.2, so i'll close this.

Couldn't find it the relevant issue in mpv's repo but based on the release notes of `v0.33.0` it's probably about Wayland
> wayland: make resizing better

I was able to test `v0.33.0` with Wayland and my extensions works fine there. So problem is limited to a Xorg session... Here is a gif:

![output](https://user-images.githubusercontent.com/53054301/113785248-44937d00-9726-11eb-9773-4a66dca6d34e.

Any way closing this issue as it's not really my bug. I am using whatever API Mutter provides for resizing a window (which is just 1 method). So I don't think I can 'fix' it with a gnome extension. 

I am compiling a list with incompatible apps at #61. So far mpv is the only known app, which doesn't work (except obvious stuff like popups etc.).

If someone has a fix/workaround or knows a tiling extension which works with mpv, feel free to comment here or directly open a pr.
