### ISSUE TITLE
Annoying window focus bug when 2+ windows are snapped against each other

### ISSUE THREAD

**Issue by Turbine1991** [Leleat/Tiling-Assist#41]
**Describe the bug**
[This issue doesn't happen when the tiling assistant plugin is disabled]

I've been coming across a rather frustrating bug which stops another window from staying ontop of a pair of snapped windows below.

**Steps To Reproduce**
- Open 3+ windows.
- Snap one window to the left and right halves of screen.
- Now pull up the third window and reposition it somewhere between them.
- Click on one of the two snapped windows and then they'll both come into focus, instead of just the one you've clicked.

**Screenshots/-captures**
![Alt Text](https://media.giphy.com/media/rXKsvq6LGLjkaRus6V/giphy.gif)

**System Info:**
 - Distro (incl. version): Pop!_OS 20.10
 - GNOME version: 3.38.3
 - Extensions version: 13
 - XOrg/Wayland: Xorg 7.7

**Comment by Leleat** [comment]
That is actually a feature and not a bug :) 

If you tile windows, you are likely to want to use them together, so they raise each other when one is focused.... Although I guess, I can make it optional.

**Comment by Turbine1991** [comment]
Oh, sorry. What are you supposed to do if you want to use a third occasional window in-front of them?

It's a lot easier to click two windows than have this feature dictate the workflow. I'm a little relieved it's not accidental, but it's been causing me interruptions all day.

**Comment by Leleat** [comment]
> What are you supposed to do if you want to use a third occasional window in-front of them?

Tile it as well. Seeing multiple windows side by side is the point of tiling after all.  Or untile the other window.

> It's a lot easier to click two windows than have this feature dictate the workflow.

Problem is that you can tile to more than just 2 tiles. And this is one of the defining features of this extension. You can also have multiple windows or one maximized window obstructing the tiles like this. Then you need to go into the overview multiple times or altTab multiple time just to get your tiles back together:

![output](https://user-images.githubusercontent.com/53054301/111200544-caa22500-85b9-11eb-9484-75097008cee3.gif)

Any way, I'll add an option to disable it later and report back once I've done it.

**Comment by Leleat** [comment]
So I've created a temporary branch https://github.com/Leleat/Tiling-Assist/tree/dont-raise-group. It doesn't add the setting yet but only disables the group raising. Please test it for a few days and tell me, if you think it's worth adding as a setting or if there are any regressions.

**Comment by Turbine1991** [comment]
> Problem is that you can tile to more than just 2 tiles. And this is one of the defining features of this extension. You can also have multiple windows or one maximized window obstructing the tiles like this. Then you need to go into the overview multiple times or altTab multiple time just to get your tiles back together:

That's a very good point. I can understand now how useful it is for those using a dock. In that case, is there a way to detect a taskbar? or is it better to provide a setting?

> Tile it as well. Seeing multiple windows side by side is the point of tiling after all. Or untile the other window.

Many windows are unable to tile, one of them is the file manager which opens with Visual Studio Code. And untiling a window each isn't the most fluid experience for those with a taskbar.

> So I've created a temporary branch https://github.com/Leleat/Tiling-Assist/tree/dont-raise-group. It doesn't add the setting yet but only disables the group raising. Please test it for a few days and tell me, if you think it's worth adding as a setting or if there are any regressions.

This branch seems to work perfectly.

**Comment by job1925** [comment]
I was coming to add a feature request for this feature to be optional and was pleased to see you are already planning a setting for this! :) Although I like the possibility of tiling to quarters (that's why I'm using this extension) I very rarely use it because I only have a 14" laptop screen. So usually I have only two windows tiled side by side.

I understand the reasoning behind this default behaviour, but sometimes it breaks my workflow too. For example, I often have Firefox tiled to the left side of the screen and code editor on the right side. Sometimes I want to take a peek at Terminal, so I bring that to the front from the overview. I may be reading some instruction for a command in Firefox, so I need to focus it. However, now my Terminal window disappears behind the code editor and I have to find it again and tile it or detach the code editor and Firefox from each other.

What about enabling this default behaviour only after there are more than two windows in a "tile group"? Or is just adding the on/off switch to extension settings more straightforward?

**Comment by Leleat** [comment]
> What about enabling this default behaviour only after there are more than two windows in a "tile group"? Or is just adding the on/off switch to extension settings more straightforward?

Not a fan of that option. Users may have different screen sizes and different tiling preferences (just like you 2 and me) so raising windows in a group at some point but not others may appear too random/like a bug as well. So I am going with a setting since that makes it clearer.

**Comment by Leleat** [comment]
Closed (by Turbine) with #44.
