### ISSUE TITLE
Gap when placing terminal

### ISSUE THREAD

**Issue by tronta** [Leleat/Tiling-Assist#51]
**Describe the bug**
When placing the terminal in a quarter or half there stays a small gap.

**Steps To Reproduce**
Open gnomw terminal and drag it to corner or side.

**Screenshots/-captures**
![grafik](https://user-images.githubusercontent.com/5135577/112220719-dda29e00-8c26-11eb-88ff-308970684470.png)

**System Info:**
 - Distro (incl. version): Fedora 34
 - GNOME version: 40

 - Extensions version: 
 - XOrg/Wayland:

**Journalctl logs**

**Additional context**

**Comment by tronta** [comment]
I saw, it's a duplicate... closed it

**Comment by Leleat** [comment]
I don't think there was an issue about the gaps from the gnome terminal yet. Well, with that being said it is not a bug but a feature (from gnome terminal). It only resizes in columns/rows. I can't change that with an extension.
