### ISSUE TITLE
Tile to center AND Tile to center 50% or 75%?

### ISSUE THREAD

**Issue by Vondelphia** [Leleat/Tiling-Assist#53]
I did not start playing around with the Layouts tab, but in the Keybindings tab, I thought it would be cool if I could assign a keyboard shortcut to "tile center" a window to the middle of the screen, OR even perhaps tile center and resize to 75%. I really like how you can tile to bottom right corner, or top left corner but why not be able to replicate that tile in middle of monitor?

:)

p.s. - it could be cool.

UPDATE: It looks like in Layouts tab, you can copy paste `0.25--0.25--0.5--0.5` into an area, save and you'll get the center 50% tile effect... :thinking:  :joy:

**Comment by Turbine1991** [comment]
I'm curious in what kind of workflow tiling an app in the center is better than tiling as full screen, half or quarter?

**Comment by Leleat** [comment]
> I thought it would be cool if I could assign a keyboard shortcut to "tile center" a window to the middle of the screen, OR even perhaps tile center and resize to 75%

> I'm curious in what kind of workflow tiling an app in the center is better than tiling as full screen, half or quarter?

What's your use case for this; do you have giant monitor or something? I am sceptical about it, too. I don't want to add more keybindings for niche/edge cases. I also can't imagine how I would want this feature to work for mouse users.

And as you said, you can (basically) do this already with layouts. The only difference to a normal keybinding is that you still need to press `Space`, `Enter` or `Middle Mouse Button` to activate the tiling (for the focused window).

**Comment by Vondelphia** [comment]
It's just a positional preference to avoid having to adjust neck / eyes. To me, it just seems logical to have a re-position, resize / tile center since most other quadrants are addressed, but I see what you are saying about niche / edge case... for sure. I love how this here Tiling app works... it's great. 

I ended up [floating around on the web some more](https://duckduckgo.com/?q=best+linux+tile+manager) and discovered other managers to find something more suitable. Funny enough it was because of that extra keypress to activate the custom layout :joy: ... you guys have a great day and enjoy. Thanks for rapid response and GLHF out there.
