### ISSUE TITLE
"Raise Group" setting not working

### ISSUE THREAD

**Issue by job1925** [Leleat/Tiling-Assist#57]
**Describe the bug**
The "Raise Group" setting always returns to being ON after closing extension settings. In addition, the setting does not seem to have any effect even if the extension setting window is left open to ensure that it remains OFF.

**Steps To Reproduce**

1. Open extension settings
2. Switch "Raise Group" off
3. Close extension settings
4. Re-open extension settings
5. Observe, that "Raise Group" is on again

**Screenshots/-captures**
![tiling_assistant](https://user-images.githubusercontent.com/64358376/112871526-0237c380-90c8-11eb-9e56-b6823095d0e8.gif)
Forgive the jump in the GIF. I believe it illustrates the problem anyway.

![tiling_assistant2](https://user-images.githubusercontent.com/64358376/112871547-06fc7780-90c8-11eb-94b5-d10a7c4ace60.gif)
This shows the other problem. When gedit is focused, the terminal gets focus too.

**System Info:**
 - Distro (incl. version): Fedora 33
 - GNOME version: 3.38.5
 - Extensions version: 14
 - XOrg/Wayland: XOrg

**Journalctl logs**
I can update these logs later, if needed.

**Additional context**
I have a couple of other extensions, but none of them are related to window management.

**Comment by Leleat** [comment]
Opps, the settings name didn't match the ui file, so the ui always used its default state and the setting wasn't affected by the ui. Fixed with the latest commit.
