### ISSUE TITLE
Option for window gap also on toggle maximize

### ISSUE THREAD

**Issue by GiovanniCardamone** [Leleat/Tiling-Assist#66]
I like left some space around the window even when there is only one window maximized.

Can you include an option to preserve window gap on "Toggle Maximization"

thanks. best regards

**Comment by Leleat** [comment]
Sure, I'll add it.

**Comment by Leleat** [comment]
Oh, I think I remember why I didn't do this originally. I can add gaps to the `Toggle Maximization` keybinding and the tiling by dragging it to the top screen edge. But it won't work for double clicking the window title bar. Do you still want this?

**Comment by GiovanniCardamone** [comment]
yes, would be nice to have anyway, for better looking desktop

**Comment by Leleat** [comment]
Implemented in current `master` branch. Will push a new version to EGO in a month (because I am still working on a new feature).

**Comment by GiovanniCardamone** [comment]
works perfectly! Thanks a lot
